# .gitleaks.toml
title = "Gitleaks configuration"

[extend]
# Inherit all 160+ default secret detection rules from Gitleaks
useDefault = true

[allowlist]
description = "Global repository allowlist"

# Stop Gitleaks from scanning specific files/folders (Regex patterns)
paths = [
    '''node_modules/''',
    '''\.git/''',
    '''package-lock\.json''',
    '''infra/.terraform/''',
    '''infra/.terraform.lock.hcl'''
]

# Stop Gitleaks from triggering on known safe generic values or false positives
regexes = [
    '''https://images\.unsplash\.com/''',
    '''FROM (node|nginx|mysql):[a-z0-9\.-]+-alpine'''
]
