resource_group_name       = "rg-name"
mysql_server_name         = "mysql-name"
database_name             = "ecommerce_store"
acr_name                  = "acr-name"
backend_image_repository  = "luxestore-backend"
frontend_image_repository = "luxestore-frontend"
image_tag                 = "latest"
db_user                   = "ecommerce_user"
